/**
 * Exports DOM components, the zero-VDOM JSX runtime, and layout helpers.
 */

export {
  DOMElement,
  type ElementOptions,
  type ElementDecorator,
} from "./element";
export {
  gradient,
  type GradientOptions,
  glow,
  type GlowOptions,
  vignette,
  type VignetteOptions,
  grain,
  type GrainOptions,
  scrim,
  type ScrimOptions,
  typewriter,
  type TypewriterOptions,
  type TypewriterStep,
  rail,
  type RailOptions,
  bracket,
  type BracketOptions,
  type BracketStyle,
} from "../decorators/index";
export {
  Title,
  Text,
  Image,
  ImageElement,
  Video,
  VideoElement,
  Webcam,
  WebcamElement,
  Shape,
  Card,
  Circle,
  Pill,
  Diamond,
  ShapeElement,
  Kicker,
  CodeBlock,
  TerminalWindow,
  BulletList,
  Table,
  Connector,
  ConnectorElement,
  Lifeline,
  LifelineElement,
  ActivationBar,
  ActivationBarElement,
  Activation,
  SequenceDiagram,
  SequenceDiagramElement,
  sequenceDiagram,
  Sequence,
  type TitleOptions,
  type TitleVariant,
  type TextOptions,
  type ImageOptions,
  type ImageFit,
  type VideoOptions,
  type WebcamOptions,
  type CameraDevice,
  type ShapeOptions,
  type ShapeKind,
  type ShapeVariant,
  type KickerOptions,
  type CodeBlockOptions,
  type CodeBlockElement,
  type TerminalWindowProps,
  type TerminalWindowElement,
  type BulletListOptions,
  type BulletListElement,
  type TableOptions,
  type TableElement,
  type ConnectorOptions,
  type ConnectorTarget,
  type ConnectorHeadType,
  type PulseOptions,
  type LifelineOptions,
  type ActivationBarOptions,
  type ActivationOptions,
  type ActivationElement,
  type SequenceDiagramOptions,
  type SequenceOptions,
} from "./components/index";
export {
  BackgroundElement,
  type BackgroundOptions,
  Starfield,
  StarfieldElement,
  type StarfieldOptions,
  AsciiFluid,
  GradientFluid,
  FluidBackgroundElement,
  type BaseFluidOptions,
  type AsciiFluidOptions,
  type GradientFluidOptions,
} from "./backgrounds/index";
export {
  arrange,
  type LayoutOptions,
  type SplitLayoutOptions,
  type RelativePlacement,
  type RelativeAlign,
  type CircleLayoutOptions,
  type GridSlot,
  type LayoutElement,
  type RuleOptions,
} from "./layout";
export {
  getPerimeterPoint,
  getTransformedPerimeterPoint,
  computeOrthogonalPath,
  computeBezierPath,
  type Point,
  type Box,
} from "./geometry";
export {
  attachRangeSelection,
  type RangeSelectionOptions,
  type RangeSelectionController,
} from "./interaction";
export {
  jsx,
  jsxs,
  jsxDEV,
  Fragment,
  createElement,
  type JSX,
} from "./jsx-runtime";
