import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      items: ["getting-started/quickstart", "getting-started/concepts"],
    },
    {
      type: "category",
      label: "Building Presentations",
      items: [
        "building/coordinates",
        "building/scenes-and-steps",
        "building/presenter-console",
        "building/animation",
        "building/layout",
        "building/visual-effects",
      ],
    },
    {
      type: "category",
      label: "Components",
      items: [
        "components/text",
        "components/card",
        "components/shapes",
        "components/bullet-list",
        "components/code-block",
        "components/terminal-block",
        "components/table",
        "components/connector",
        "components/icons-and-images",
        "components/video",
        "components/sequence-diagram",
      ],
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        "advanced/custom-components",
        "advanced/lifecycle",
        "advanced/custom-decorators",
        "advanced/theming",
        {
          type: "link",
          label: "Brand & Visual System",
          href: "/stageroutine/brand",
        },
        "advanced/overlays-and-events",
        "advanced/custom-paths",
        "advanced/patterns",
        "advanced/under-the-hood",
      ],
    },
    {
      type: "category",
      label: "API Reference",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
